# Generated by Django 5.0.9 on 2024-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvnApp', '0005_alter_usersubscription_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.FileField(upload_to='video_courses/')),
                ('deadline', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Video_courses',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
