# Generated by Django 5.0.9 on 2024-09-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvnApp', '0006_tasks_remove_userprogress_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='price',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
