# Generated by Django 5.0.9 on 2024-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvnApp', '0007_alter_tasks_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='reference',
            field=models.FileField(blank=True, null=True, upload_to='video_courses/'),
        ),
    ]
